//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoviesActor
    {
        public int Id { get; set; }
        public int MovieId { get; set; }
        public Nullable<int> ActorId { get; set; }
    
        public virtual Movy Movy { get; set; }
        public virtual ProducersActor ProducersActor { get; set; }
    }
}
